services:
  frontend:
    build:
      context: ./ChefFrontend
      dockerfile: Dockerfile
    ports:
      - "80:80"  
    depends_on:
      - backend

  backend:
    build:
      context: ./ChefBackend
      dockerfile: Dockerfile
    ports:
      - "5218:8080"  
    environment:
      - ASPNETCORE_ENVIRONMENT=PRODUCTION
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
      - MONGO_DATABASE=ChefClause
      - MONGO_COLLECTION=Recipes
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - chef-mongo-data:/data/db

volumes:
  chef-mongo-data: 