version: '3'
services:
  backend:
    build:
      context: ./ChefBackend
      dockerfile: Dockerfile
    image: sherry3333/chef-backend:latest
    env_file:
      - ./ChefBackend/.env
    ports:
      - "5218:8080"

  frontend:
    build:
      context: ./ChefFrontend
      dockerfile: Dockerfile
    image: sherry3333/chef-frontend:latest
    env_file:
      - ./ChefFrontend/.env
    ports:
      - "80:80"
   
   
