name: Deploy Backend to Render

# Trigger this workflow only when code changes are pushed to the main branch
# and those changes are within the ChefBackend folder.
on:
  push:
    branches: [ main ]
    paths:
      - 'ChefBackend/**'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST https://api.render.com/deploy/srv-d1kajtje5dus73e9sc6g \
          -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}'