name: CI/CD Deploy to EC2 with Docker Compose

on:
  push:
    branches: [ main ]
    paths:
      - 'ChefBackend/**'
      - 'ChefFrontend/**'
      - 'docker-compose.yml'
      - 'docker-compose.prod.yml'
      - '.github/workflows/deploy.yml'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.filter.outputs.frontend }}
      backend_changed: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'ChefFrontend/**'
            backend:
              - 'ChefBackend/**'

  build-push-backend:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.backend_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build backend Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chef-backend:latest ./ChefBackend

      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/chef-backend:latest

  build-push-frontend:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build frontend Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chef-frontend:latest ./ChefFrontend

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/chef-frontend:latest

  deploy-ec2:
    runs-on: ubuntu-latest
    needs: [build-push-backend, build-push-frontend, detect-changes]
    if: always()  # allow all jobs to run 
    steps:
      - name: Deploy on EC2 with docker-compose.prod.yml
        if: needs.detect-changes.outputs.backend_changed == 'true' || needs.detect-changes.outputs.frontend_changed == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml up -d
